# Plugins
gems:
- jekyll-sitemap
safe: false

port: 80

#other commands
encoding: utf-8


# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG Italia"
email: "gdgItalia@email.com"
description: "Google Developer Group Italia"
baseurl: "/gdgIT"
url: "https://gdgitalia.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Italy"
organizerAlternateName: "Google Developer Group Italia"
organizerDescription: "I Google Developer Groups (GDG) sono gruppi di persone interessate alla tecnologia Google, possono assumere tante forme -- da gruppi di poche persone che si incontrano per parlare di tecnologia a grandi seminari, codelabs o hackatons"
organizerEmail: "none@none.it"
organizerLogo: "/img/seo/GDGitaly-logo.png"
organizerLink: "http://gdgitalia.org/"

# Head
metaKeywords: "events, eventi, gdg, google, programming, programmazion, android, chrome, developers, sviluppatori, italy, italia"
twitterAccount: "@gdgItalia"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
#TODO, SISTEMARE LA CARTELLA
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/events/", text: "Eventi"}
# - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/GDGs/", text: "GDG's"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://developers.google.com/groups/directory/Italy", text: "Trova il tuo GDG"}
rightNavigationButtons:
 - {link: "https://developers.google.com/groups/directory/Italy", text: "Trova il tuo GDG"}

# Hero Block
heroImage: "nice.jpg"
heroTitle: "GDG <typeout>"
maintitle: "Google Developer Group"
typeoutTextValues: '"Torino","Palermo","Campania","Catania","Gela","Bari","ReggioEmilia","Cosenza","Milan","Nebrodi","Pisa","Firenze","ReggioCalabia","Roma Lab","Trento","Ancona","Brescia","Genova","Sardegna","Venezia","Bologna","Camerino","Udine","Parma","Perugia","Pescara"'
typeoutFallback: "Italia"
heroButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#- {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "I Gooogle Developer Groups sono gruppi indipendenti sparsi in tutto il mondo composti da persone interessate nella tecnologia che amano condividere le loro esperienze e conoscenze."
aboutDescription: "In italia sono presenti 24 GDG, se vuoi farne parte ti basta cercare il GDG più vicino a te."
aboutBlock:
 - {title: "Eventi Google", image: "conference.jpg", text: "Gli eventi Google più importanti organizzati per te dai GDG! Tanti speakers e tanto divertimento!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Il modo migliore per fare esperienza si fa programmando, meglio se tutti assieme!" }
 - {title: "Seminari", image: "talks.JPG", text: "Tanti seminari sulle tue tecnologie preferite!" }
 - {title: "Community", image: "community.JPG", text: "Trova GDG più vicino a te!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "5000", specialCharacter: "+", info: "partecipanti", detail: "negli ultimi 6 mesi"}
 - {count: "50", specialCharacter: "+", info: "Eventi", detail: "negli ultimi 6 mesi"}
 - {count: "24", specialCharacter: "", info: "GDG", detail: "in tutta italia"}
 #- {count: "1", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "News"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Hashtag us!"
twitterHashTag: "GDGItalia"
#TODO! 
twitterFeed: ""

# Partners Block
organizersTitle: "Organizzatori"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Diventa uno sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Iscriviti per avere i nostri aggiornamenti"
#TODO
subscribeAction: ""
subscribeInfo: "Registra la tua mail per ricevere informazioni da GDG Italia!"



# Footer
socialLinks:
 - {link: "https://plus.google.com/109399456192014388090", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGItalia", icon: "twitter"}
 - {link: "https://facebook.com/GDGItalia", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://developersitalia.blogspot.it/", text: "Google Developers Italia"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:italy@gdg.mail.it", text: "italy@gdg.mail.it"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Segui i nostri eventi"
blogCommentsEnabled: true
discusShortName: "GDGItalia"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Chi siamo"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

